CartoonWeb/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.popup_card.urls', namespace='popup_card')),
    url(r'^public/api/ws/', include('api.urls', namespace='api_ws'))
    # url(r'^', include('apps.popup_admin.urls', namespace='admin_card')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url

from api.views import hello_world, comment_list, CommentList

urlpatterns = [
    url(r'^commets/', CommentList.as_view(), name='ws_comments_all')
    # url(r'^commets/(?P<slug>[-\w]+)/$', comment_list, name='ws_comments_all')
]

apps/popup_card/urls.py
from django.conf.urls import url

from apps.popup_card.views import hello_world, ViewPopupCard, ViewInvitationCard, DetailPopupCard, \
    ListPopupCardByCategory, ListInvitationCardByCategory, DetailInvitationCard

urlpatterns = [
    url(r'^$', hello_world, name='hello_world'),
    url(r'^products/popup-card/$', ViewPopupCard.as_view(), name='popup_card_list'),
    url(r'^products/popup-card/p/(?P<slug>[-\w]+)/$', DetailPopupCard.as_view(), name='popup_card_detail'),
    url(r'^products/popup-card/c/(?P<slug>[-\w]+)/$', ListPopupCardByCategory.as_view(), name='card_list_by_category'),
    url(r'^products/invitation-card/$', ViewInvitationCard.as_view(), name='invitation_card_list'),
    url(r'^products/invitation-card/(?P<slug>[-\w]+)/$', DetailInvitationCard.as_view(), name='invitation_card_detail'),
    url(r'^products/invitation-card/(?P<cat>[-\w]+)/$', ListInvitationCardByCategory.as_view(), name='invitation_card_list_by_category'),
]

apps/popup_card/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

from business.base.Enums import EnumCategory
from business.base.models import Type_general, Tag_general, BaseEntity, Status_general


# Create your models here.
class Category_card(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=500, unique=True)
    status = models.ForeignKey(Status_general)

    def __str__(self):
        return self.name

class Status_price(models.Model):
    name = models.CharField(max_length=50)
    abbreviation = models.CharField(max_length=5)

    def __str__(self):
        return self.name

class Popup_card(BaseEntity, models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=500, unique=True)
    description = models.TextField(blank=True)
    type = models.ForeignKey(Type_general, null=True, blank=True)
    tag = models.ManyToManyField(Tag_general)
    category = models.ForeignKey(Category_card, null=True, blank=True)
    image = models.ImageField(upload_to='card-popup', blank=True)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('create_date',)

class Popup_card_catalog(BaseEntity, models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=500,unique=True)
    type = models.ForeignKey(Type_general, null=True, blank=True)
    tag = models.ManyToManyField(Tag_general)
    card = models.ManyToManyField(Popup_card)

    def __str__(self):
        return self.name

class Price_popup_card(models.Model):
    description = models.CharField(max_length=200, null=True)
    start_date = models.DateTimeField('Init Price')
    end_date = models.DateTimeField('Finish Price')
    status = models.ForeignKey(Status_price)
    price = models.DecimalField(max_digits=21,decimal_places=5)
    percentage_discount = models.SmallIntegerField(null=True)
    quantity_discount = models.DecimalField(max_digits=18, decimal_places=2)

class Comment(BaseEntity, models.Model):
    content = models.TextField()
    card_post = models.ForeignKey(Popup_card)
    commend_related = models.BigIntegerField(null=True, blank=True)
    is_reply = models.BooleanField(default=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ('create_date',)

class Like(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    card_post = models.ForeignKey(Popup_card)
    user_click = models.ForeignKey(User)
    is_like = models.BooleanField(default=True)

apps/popup_card/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# import the logging library
# import logging

from django.http import HttpResponse
from django.shortcuts import render

from django.views.generic import DetailView, ListView

from apps.popup_card.models import Popup_card, Category_card, Comment
from business.base.Enums import EnumType, EnumStatus

# Get an instance of a logger
# logger = logging.getLogger(__name__)

from business.base.models import Tag_general

# Create your views here.
def hello_world(req):
    return render(req, 'popup_card/index.html')

def get_all_categories_active():
    return Category_card.objects.filter(status=EnumStatus.Active)

def get_comments_by_id_active(req):
    return Comment.objects.filter(card_post=req, status=EnumStatus.Active)

class ViewPopupCard(ListView):
    model = Popup_card
    template_name = 'popup_card/list_paper_cards.html'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(ViewPopupCard, self).get_context_data(**kwargs)
        context['categories'] = get_all_categories_active()
        return context

    def get_queryset(self):
        return Popup_card.objects.filter(status=EnumType.CardPopup)

class ViewInvitationCard(ListView):
    model = Popup_card
    template_name = 'popup_card/list_paper_cards.html'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(ViewInvitationCard, self).get_context_data(**kwargs)
        context['categories'] = get_all_categories_active()
        return context

    def get_queryset(self):
        return Popup_card.objects.filter(status=EnumType.InvitationCard)

class DetailPopupCard(DetailView):
    model = Popup_card
    template_name = 'popup_card/detail_paper_cards.html'
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super(DetailPopupCard, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']
        card = self.model.objects.filter(url=slug)
        context['card'] = card
        context['comments'] = get_comments_by_id_active(req=card)
        context['tags'] = Tag_general.objects.all()
        context['categories'] = get_all_categories_active()
        return context

class DetailInvitationCard(DetailView):
    model = Popup_card
    template_name = 'popup_card/detail_paper_cards.html'
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super(DetailInvitationCard, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']
        card = self.model.objects.filter(url=slug)
        context['card'] = card
        context['tags'] = Tag_general.objects.all()
        return context

class ListPopupCardByCategory(ListView):
    model = Popup_card
    template_name = 'popup_card/list_paper_cards.html'
    paginate_by = 8
    slug_field = 'cat'

    def get_context_data(self, **kwargs):
        context = super(ListPopupCardByCategory, self).get_context_data(**kwargs)
        context['categories'] = get_all_categories_active()
        return context

    def get_queryset(self):
        category = self.kwargs['slug']
        if category == 'all':
            return Popup_card.objects.filter(status=EnumType.CardPopup)
        else:
            return Popup_card.objects.filter(status=EnumType.CardPopup, category__url=category)

class ListInvitationCardByCategory(ListView):
    model = Popup_card
    template_name = 'popup_card/list_paper_cards.html'
    paginate_by = 8
    slug_field = 'cat'

    def get_context_data(self, **kwargs):
        context = super(ListInvitationCardByCategory, self).get_context_data(**kwargs)
        context['categories'] = get_all_categories_active()
        return context

    def get_queryset(self):
        category = self.kwargs['slug']
        if category == 'all':
            return Popup_card.objects.filter(status=EnumType.InvitationCard)
        else:
            return Popup_card.objects.filter(status=EnumType.InvitationCard, category__url=category)

apps/templates/popup_card/detail_paper_cards.html
{% extends 'base/page-master/main-master.html' %}
{% load staticfiles %}

{% block title %}
    Details Product
{% endblock %}

{% block content %}

    <section id="page-breadcrumb">
        <div class="vertical-center sun">
            <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12">
                            <h1 class="title">Portfolio</h1>
                            <p>Be Creative</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/#action-->


    {% for object in card %}
        <section id="blog-details" class="padding-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 col-sm-7">
                        <div class="post-thumb">
                            <div class="col-sm-6">
                                {% if popup_card.image %}
                                    <img src="/resource/{{ object.image }}" class="img-responsive"
                                         alt="{{ object.name }}">
                                {% else %}
                                    <img src="{% static 'assets/triangle/images/portfolio/1.jpg' %}"
                                         class="img-responsive"
                                         alt="">
                                {% endif %}
                            </div>
                            <div class="col-sm-6">
                                <div class="project-name overflow">
                                    <h2 class="bold">{{ object.title }}</h2>
                                    <ul class="nav navbar-nav navbar-default">
                                        <li><a href="#"><i class="fa fa-clock-o"></i>{{ object.create_date }}</a></li>
                                        <li><a href="#"><i class="fa fa-tag"></i>{{ object.type.name }}</a></li>
                                    </ul>
                                </div>
                                <div class="project-info overflow">
                                    <h3>{{ object.name }}</h3>
                                    <p>{{ object.description }}</p>
                                </div>
                                <div class="skills overflow">
                                    <h3>Tags</h3>
                                    <ul class="nav navbar-nav navbar-default">
                                        {% for tag in tags %}
                                            <li><a href="#"><i class="fa fa-check-square"></i>{{ tag.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="live-preview">
                                    <a href="{% url 'popup_card:popup_card_list' %}" class="btn btn-common uppercase">Back
                                        list</a>
                                </div>
                            </div>
                        </div>
                        <div class="post-content overflow">
                            <div class="post-bottom overflow">
                                <ul class="nav navbar-nav post-nav">
                                    <li><a href="#"><i class="fa fa-tag"></i>Creative</a></li>
                                    <li><a href="#"><i class="fa fa-heart"></i>32 Love</a></li>
                                    <li><a href="#"><i class="fa fa-comments"></i>3 Comments</a></li>
                                </ul>
                            </div>
                            <div class="blog-share">
                                <span class='st_facebook_hcount'></span>
                                <span class='st_twitter_hcount'></span>
                                <span class='st_linkedin_hcount'></span>
                                <span class='st_pinterest_hcount'></span>
                                <span class='st_email_hcount'></span>
                            </div>
                            <div class="response-area">
                                <h2 class="bold">Comments</h2>
                                <ul class="media-list">
                                    <li class="media" id="content-comment">
                                        {% for comment in comments %}
{#                                            {% if comment.is_reply %}#}
{#                                                <div class="post-comment">#}
{#                                                    <a class="pull-left" href="#">#}
{#                                                        <img class="media-object" src="images/blogdetails/2.png" alt="">#}
{#                                                    </a>#}
{#                                                    <div class="media-body">#}
{#                                                        <span><i class="fa fa-user"></i>Posted by <a href="#">Endure</a></span>#}
{#                                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed#}
{#                                                            do#}
{#                                                            eiusmod#}
{#                                                            tempor incididunt ut labore et dolore magna aliq Ut enim ad#}
{#                                                            minim#}
{#                                                            veniam, quis nostrud exercitation ullamco laboris nisi.</p>#}
{#                                                        <ul class="nav navbar-nav post-nav">#}
{#                                                            <li><a href="#"><i class="fa fa-clock-o"></i>February#}
{#                                                                11,2014</a>#}
{#                                                            </li>#}
{#                                                            <li><a href="#"><i class="fa fa-reply"></i>Reply</a></li>#}
{#                                                        </ul>#}
{#                                                    </div>#}
{#                                                </div>#}
{#                                            {% else %}#}
{#                                                <div class="parrent">#}
{#                                                    <ul class="media-list">#}
{#                                                        <li class="post-comment reply">#}
{#                                                            <a class="pull-left" href="#">#}
{#                                                                <img class="media-object" src="images/blogdetails/3.png" alt="">#}
{#                                                            </a>#}
{#                                                            <div class="media-body">#}
{#                                                                <span><i class="fa fa-user"></i>Posted by <a href="#">Endure</a></span>#}
{#                                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing#}
{#                                                                    elit, sed#}
{#                                                                    do#}
{#                                                                    eiusmod tempor incididunt ut </p>#}
{#                                                                <ul class="nav navbar-nav post-nav">#}
{#                                                                    <li><a href="#"><i class="fa fa-clock-o"></i>February#}
{#                                                                        11,2014</a></li>#}
{#                                                                </ul>#}
{#                                                            </div>#}
{#                                                        </li>#}
{#                                                    </ul>#}
{#                                                </div>#}
{#                                            {% endif %}#}
                                        {% endfor %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-5">
                        <div class="sidebar blog-sidebar">
                            <div class="sidebar-item categories">
                                <h3>Categories</h3>
                                <ul class="nav navbar-stacked">
                                    {% for category in categories %}
                                        <li id="{{ category.url }}"><a
                                                href="{% url 'popup_card:card_list_by_category' category.url %}">{{ category.name }}<span
                                                class="pull-right">(1)</span></a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="sidebar-item tag-cloud">
                                <h3>Tag Cloud</h3>
                                <ul class="nav nav-pills">
                                    <li><a href="#">Corporate</a></li>
                                    <li><a href="#">Joomla</a></li>
                                    <li><a href="#">Abstract</a></li>
                                    <li><a href="#">Creative</a></li>
                                    <li><a href="#">Business</a></li>
                                    <li><a href="#">Product</a></li>
                                </ul>
                            </div>
                            <div class="sidebar-item popular">
                                <h3>Latest Photos</h3>
                                <ul class="gallery">
                                    <li><a href="#"><img
                                            src="{% static 'assets/triangle/images/portfolio/popular1.jpg' %}"
                                            alt=""></a></li>
                                    <li><a href="#"><img
                                            src="{% static 'assets/triangle/images/portfolio/popular2.jpg' %}"
                                            alt=""></a></li>
                                    <li><a href="#"><img
                                            src="{% static 'assets/triangle/images/portfolio/popular3.jpg' %}"
                                            alt=""></a></li>
                                    <li><a href="#"><img
                                            src="{% static 'assets/triangle/images/portfolio/popular4.jpg' %}"
                                            alt=""></a></li>
                                    <li><a href="#"><img
                                            src="{% static 'assets/triangle/images/portfolio/popular5.jpg' %}"
                                            alt=""></a></li>
                                    <li><a href="#"><img
                                            src="{% static 'assets/triangle/images/portfolio/popular1.jpg' %}"
                                            alt=""></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endfor %}

    <!--/#portfolio-information-->

    <!-- Start Handlebars -->
    {% verbatim %}
    <script type="text/x-handlebars-template" id="entry-commend">
        {{# each request}}
            <div class="post-comment">
                <a class="pull-left" href="#">
                    <img class="media-object" src="images/blogdetails/2.png" alt="">
                </a>
                <div class="media-body">
                    <span><i class="fa fa-user"></i>Posted by <a href="#">{{ create_user }}</a></span>
                    <p>{{ content }}</p>
                    <ul class="nav navbar-nav post-nav">
                        <li><a href="#"><i class="fa fa-clock-o"></i>{{ create_date }}</a></li>
                        {{#if is_reply}}
                        <li><a href="#"><i class="fa fa-reply"></i>Reply</a></li>
                        {{/if}}
                    </ul>
                </div>
            </div>
        {{/each}}
    </script>
    {% endverbatim %}
    <!-- End Handlebars -->


{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'popup_card/js/detail_paper_js.js' %}"></script>
{% endblock %}

apps/templates/popup_card/list_paper_cards.html
{% extends 'base/page-master/main-master.html' %}
{% load staticfiles %}

{% block title %}
    All Popup Card
{% endblock %}

{% block extras_static %}
    <link rel="stylesheet" href="{% static 'popup_card/css/customer.css' %}">
{% endblock %}

{% block content %}

    <section id="page-breadcrumb">
        <div class="vertical-center sun">
            <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12">
                            <h1 class="title">Portfolio</h1>
                            <p>Be Creative</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/#action-->


    <section id="blog" class="padding-top">
        <div class="container">

            {% if object_list %}
                <div class="row">
                    <div class="col-md-9 col-sm-7">
                        <div class="row">
                            {% for popup_card in object_list %}
                                <div class="col-md-6 col-sm-12 blog-padding-right">
                                    <div class="single-blog two-column">
                                        <div class="post-thumb">
                                            <a href="{% url 'popup_card:popup_card_detail' popup_card.url %}">
                                                {% if popup_card.image %}
                                                    <img src="/resource/{{ popup_card.image }}" class="img-responsive" alt="{{ category.name }}">
                                                {% else %}
                                                    <img src="{% static 'assets/triangle/images/portfolio/1.jpg' %}" class="img-responsive" alt="{{ category.name }}">
                                                {% endif %}
                                            </a>
                                            <div class="post-overlay">
                                                <span class="uppercase"><a href="#">14 <br><small>Feb</small></a></span>
                                            </div>
                                        </div>
                                        <div class="post-content overflow">
                                            <h2 class="post-title bold"><a
                                                    href="{% url 'popup_card:popup_card_detail' popup_card.url %}">{{ popup_card.title }}</a>
                                            </h2>
                                            <h3 class="post-author"><a href="#">{{ popup_card.name }}</a></h3>
                                            <p>{{ popup_card.description }}</p>
                                            <a href="{% url 'popup_card:popup_card_detail' popup_card.url %}"
                                               class="read-more">View More</a>
                                            <div class="post-bottom overflow">
                                                <ul class="nav nav-justified post-nav">
                                                    <li><a href="#"><i class="fa fa-tag"></i>{{ popup_card.type.name }}
                                                    </a>
                                                    </li>
                                                    <li><a href="#"><i class="fa fa-heart"></i>32 Love</a></li>
                                                    <li><a href="#"><i class="fa fa-comments"></i>3 Comments</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        {% if paginator %}
                            <div class="row">
                                <div class="portfolio-pagination">
                                    <ul class="pagination">
                                        <li>
                                            {% if page_obj.has_previous %}
                                                <a href="?page={{ page_obj.previous_page_number }}">left</a>
                                            {% endif %}
                                        </li>
                                        {% for i in  paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class="active"><a href="#">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        <li>
                                            {% if page_obj.has_next %}
                                                <a href="?page={{ page_obj.next_page_number }}">right</a>
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-3 col-sm-5">
                        <div class="sidebar blog-sidebar">
                            <div class="sidebar-item categories">
                                <h3>Categories</h3>
                                <ul class="nav navbar-stacked">
                                    {% for category in categories %}
                                    <li id="{{ category.url }}"><a href="{% url 'popup_card:card_list_by_category' category.url %}">{{ category.name }}<span class="pull-right">(1)</span></a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="sidebar-item tag-cloud">
                                <h3>Tag Cloud</h3>
                                <ul class="nav nav-pills">
                                    <li><a href="#">Corporate</a></li>
                                    <li><a href="#">Joomla</a></li>
                                    <li><a href="#">Abstract</a></li>
                                    <li><a href="#">Creative</a></li>
                                    <li><a href="#">Business</a></li>
                                    <li><a href="#">Product</a></li>
                                </ul>
                            </div>
                            <div class="sidebar-item popular">
                                <h3>Latest Photos</h3>
                                <ul class="gallery">
                                    <li><a href="#"><img src="{% static 'assets/triangle/images/portfolio/popular1.jpg' %}" alt=""></a></li>
                                    <li><a href="#"><img src="{% static 'assets/triangle/images/portfolio/popular2.jpg' %}" alt=""></a></li>
                                    <li><a href="#"><img src="{% static 'assets/triangle/images/portfolio/popular3.jpg' %}" alt=""></a></li>
                                    <li><a href="#"><img src="{% static 'assets/triangle/images/portfolio/popular4.jpg' %}" alt=""></a></li>
                                    <li><a href="#"><img src="{% static 'assets/triangle/images/portfolio/popular5.jpg' %}" alt=""></a></li>
                                    <li><a href="#"><img src="{% static 'assets/triangle/images/portfolio/popular1.jpg' %}" alt=""></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="text-center">
                    <h2>We do not have products :(</h2>
                    <p>Soon we will be offering what you are looking for</p>
                    <a href="#" class="btn btn-error">RETURN TO THE HOMEPAGE</a>
                </div>
            {% endif %}
        </div>
    </section>
    <!--/#blog-->

{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'assets/triangle/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/triangle/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/triangle/js/jquery.isotope.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/triangle/js/lightbox.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/triangle/js/wow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/triangle/js/main.js' %}"></script>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'popup_card/js/trujillodev-custom.js' %}"></script>
{% endblock %}